name: 'ThunderstoreCLI - TEST'
description: 'A Github action for the Thunderstore CLI - TEST'
branding:
  icon: server
  color: blue
inputs:
  package-version:
    description: 'Version number for the package.'
    required: true
  token:
    description: 'Authentication token to use for publishing.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - 'publish'
  - --package-version
  - ${{ inputs.package-version }}
  - '--token'
  - ${{ inputs.token }}
