name: 'ThunderstoreCLI - TEST'
description: 'A Github action for the Thunderstore CLI - TEST'
branding:
  icon: server
  color: blue
inputs:
  args:
    description: 'publish args, example : --token tss_XXX'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - 'publish'
  - ${{ inputs.args }}
